name: updateRules

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Lancement manuel du service
  workflow_dispatch:
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: "push rules PresenceZone on qualimarc API"
      uses: fjogeleit/http-request-action@v1
      with:
      #Lien du ws pour sauvegarder les regles de qualimarque
        url: "http://colormind.io/api/"
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json"}'
        bearerToken: "${{ secrets.token }}"

        #le fichier du dépot github
        files: '${{ github.workspace }}/rulesStructurePresenceZone.yaml'
        #        data: '{model : "default",input : [[44,43,44],[90,83,82],"N","N","N"]}'
        #        files: "${{ github.workspace }}/test.json"
