name: updateRules

env:
  URL_API_QUALIMARC: https://qualimarc-test.sudoc.fr/api/v1/indexRules

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Lancement manuel du service
  workflow_dispatch:

# jobs:
#   deployment:
#     runs-on: ubuntu-latest
#     steps:
#       - name: "push rules PresenceZone on qualimarc API"
#         run: |
#           cat rulesStructurePresenceZone.yaml | curl -X POST -H "Content-Type: text/yaml" -H "Authorization: Bearer ${{ secrets.QUALIMARC_API_INDEX_RULE_TOKEN }}" --data-binary @- ${{ env.URL_API_QUALIMARC }}

#       - name: "push rules PresenceSousZone on qualimarc API"
#         run: |
#           cat rulesStructurePresenceSousZone.yaml | curl -X POST -H "Content-Type: text/yaml" -H "Authorization: Bearer ${{ secrets.QUALIMARC_API_INDEX_RULE_TOKEN }}" --data-binary @- ${{ env.URL_API_QUALIMARC }}

#       - name: "push rules NombreZone on qualimarc API"
#         run: |
#           cat rulesStructureNombreZone.yaml | curl -X POST -H "Content-Type: text/yaml" -H "Authorization: Bearer ${{ secrets.QUALIMARC_API_INDEX_RULE_TOKEN }}" --data-binary @- ${{ env.URL_API_QUALIMARC }}

#       - name: "push rules NombreSousZone on qualimarc API"
#         run: |
#           cat rulesStructureNombreSousZone.yaml | curl -X POST -H "Content-Type: text/yaml" -H "Authorization: Bearer ${{ secrets.QUALIMARC_API_INDEX_RULE_TOKEN }}" --data-binary @- ${{ env.URL_API_QUALIMARC }}
